version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: pacientus/telega_py_repo:second
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - '/app/node_modules'
    depends_on:
      - mysql_server

  mysql_server:
    image: mysql:latest
    environment:
      - TELEGRAM_TOKEN=6001752286:AAHjw_f-goQybtD3H7ItYwg90UtsX2T3gIA
      - MYSQL_DATABASE=telega_py_db
      - MYSQL_USER=kir
      - MYSQL_PASSWORD=qwqwQWQW
      - MYSQL_ROOT_PASSWORD=qwqwQWQW
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

